In [15]:
import pandas as pd

In [16]:
from io import StringIO
csv_data = '''A,B,C,D
1.0,2.0,3.0,4.0
5.0,6.0,99.0,8.0
10.0,11.0,12.0
32.0,,22.0
43.0,,2.0'''

In [17]:
df = pd.read_csv(StringIO(csv_data))

In [18]:
df

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0  99.0  8.0
2  10.0  11.0  12.0  NaN
3  32.0   NaN  22.0  NaN
4  43.0   NaN   2.0  NaN

In [19]:
df.isnull().sum()

A    0
B    2
C    0
D    3
dtype: int64

In [20]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12., nan],
       [32., nan, 22., nan],
       [43., nan,  2., nan]])

droping row

In [21]:
df.dropna(axis=0) #for row

A    B     C    D
0  1.0  2.0   3.0  4.0
1  5.0  6.0  99.0  8.0

droping col

In [22]:
df.dropna(axis = 0) #for col

A    B     C    D
0  1.0  2.0   3.0  4.0
1  5.0  6.0  99.0  8.0

In [23]:
from sklearn.impute import SimpleImputer


In [25]:
import numpy as np
imr = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12.,  4.],
       [32.,  2., 22.,  4.],
       [43.,  2.,  2.,  4.]])

In [29]:
imr = SimpleImputer(missing_values=np.nan, strategy='mean')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        , 99.        ,  8.        ],
       [10.        , 11.        , 12.        ,  6.        ],
       [32.        ,  6.33333333, 22.        ,  6.        ],
       [43.        ,  6.33333333,  2.        ,  6.        ]])

In [31]:
imr = SimpleImputer(missing_values=np.nan, strategy='median')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6., 99.,  8.],
       [10., 11., 12.,  6.],
       [32.,  6., 22.,  6.],
       [43.,  6.,  2.,  6.]])

In [32]:
df.fillna(df.mean())

A          B     C    D
0   1.0   2.000000   3.0  4.0
1   5.0   6.000000  99.0  8.0
2  10.0  11.000000  12.0  6.0
3  32.0   6.333333  22.0  6.0
4  43.0   6.333333   2.0  6.0

In [33]:
df.fillna(df.median())

A     B     C    D
0   1.0   2.0   3.0  4.0
1   5.0   6.0  99.0  8.0
2  10.0  11.0  12.0  6.0
3  32.0   6.0  22.0  6.0
4  43.0   6.0   2.0  6.0

In [36]:
imr = SimpleImputer(missing_values=np.nan, strategy='')
imr = imr.fit(df.values)
imputed_data = imr.transform(df.values)
imputed_data

InvalidParameterError: The 'strategy' parameter of SimpleImputer must be a str among {'constant', 'mean', 'median', 'most_frequent'}. Got 'mod' instead.