In [1]:
import numpy as np

In [3]:
np_array = np.array([19,15,17,26])
np_sqrt = np.sqrt(np_array)
np_sqrt

array([4.35889894, 3.87298335, 4.12310563, 5.09901951])

In [4]:
np.cos(0)

1.0

In [5]:
from numpy import pi

In [6]:
np.sin(pi/2)

1.0

In [7]:
np.cos(pi)

-1.0

In [8]:
np.floor([1.5,2.6,3.6])

array([1., 2., 3.])

In [9]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])