In [1]:
import numpy as np

In [5]:
distance = np.array([10,15,17,26])
time = np.array([0.3,0.47,0.55,1.20])


In [8]:
np_speed = distance / time
np_speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [11]:
np_city = np.array([['NYC','LA','Mianmi','Houston'],['NY','CA','FA','TX']])


In [12]:
np_city.ndim

2

In [13]:
np_city.shape

(2, 4)

In [14]:
#shape 

In [16]:
first_trail_cyclist = [10,15,17,26]
second_trail_cyclist = [12,11,21,24]


In [17]:
np_first_trail_cyclist = np.array(first_trail_cyclist)
np_second_trail_cyclist = np.array(second_trail_cyclist)

In [19]:
total_distance = np_first_trail_cyclist + np_second_trail_cyclist
total_distance

array([22, 26, 38, 50])

Access the array elements

In [20]:
cyclist_trails = np.array([[10,15,17,26],[12,11,21,24]])

In [21]:
first_trail = cyclist_trails[0]
first_trail

array([10, 15, 17, 26])

In [22]:
second_trail = cyclist_trails[1]
second_trail

array([12, 11, 21, 24])

In [23]:
first_cyclist_all_trails = cyclist_trails[:,0];
first_cyclist_all_trails

array([10, 12])

In [24]:
cyclist_trails.shape

(2, 4)

In [25]:
two_cyclist_trails_data = cyclist_trails[:,1:3]
two_cyclist_trails_data

array([[15, 17],
       [11, 21]])

In [26]:
#Accessing array elements : iterations
for i in cyclist_trails:
  print(i)

[10 15 17 26]
[12 11 21 24]


In [27]:
for i in two_cyclist_trails_data:
  print(i)

[15 17]
[11 21]


#indexing with boolean array

In [28]:
test_scores = np.array([45,72,89,56,24]);
pass_score = test_scores > 60
pass_score

array([False,  True,  True, False, False])

In [29]:
test_scores[pass_score]

array([72, 89])

In [32]:
pass_score & ~pass_score

array([False, False, False, False, False])