<h1> shape Manipulation <h1>
<h3> ravel, split,flatten,resize, reshape,stack,<h3>

In [2]:
import numpy as np

In [3]:
cyclist_trails = np.array([[10,15,17,26],[12,11,21,24]])
cyclist_trails

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [4]:
new_oneD_array = cyclist_trails.ravel()
new_oneD_array

array([10, 15, 17, 26, 12, 11, 21, 24])

In [7]:
print(cyclist_trails)
print(new_oneD_array)

[[10 15 17 26]
 [12 11 21 24]]
[10 15 17 26 12 11 21 24]


In [8]:
#flattening
ne_oneD_array = cyclist_trails.flatten()
print(ne_oneD_array)
print(cyclist_trails)

[10 15 17 26 12 11 21 24]
[[10 15 17 26]
 [12 11 21 24]]


In [9]:
new_oneD_array is cyclist_trails

False

In [10]:
ne_oneD_array is cyclist_trails

False

<h3> reshape <h3>
not chagning original

In [15]:
new_oneD_array.reshape((4,2))

array([[10, 15],
       [17, 26],
       [12, 11],
       [21, 24]])

In [16]:
print(new_oneD_array)

[10 15 17 26 12 11 21 24]


<h3> <h3>
Hsplit


In [17]:
np.hsplit(new_oneD_array,2)

[array([10, 15, 17, 26]), array([12, 11, 21, 24])]