In [54]:
import numpy as np

In [55]:
x, y = np.array([[1],[-2]]), np.array([[5],[7]])

In [56]:
cos_theta = (x.T @ y) / (np.linalg.norm(x,2)) * (np.linalg.norm(y,2))

print(cos_theta)

[[-34.62369131]]


In [62]:
np.round(cos_theta,3)

array([[-34.624]])

cos inverse

In [61]:
cos_inverse = np.arccos(cos_theta)
cos_inverse

C:\Users\himan\AppData\Local\Temp\ipykernel_13108\2902228494.py:1: RuntimeWarning: invalid value encountered in arccos
  cos_inverse = np.arccos(cos_theta)


array([[nan]])

In [59]:
degree  = cos_theta * ((100)/np.pi)
degree

array([[-1102.10632405]])