In [50]:
import numpy as np

In [51]:
x = np.array([[1],[2],[3]])


In [52]:
x.shape

(3, 1)

In [53]:
print(f"A 3-D vector: \n {x}")

A 3-D vector: 
 [[1]
 [2]
 [3]]


In [54]:
y = np.array([[1],[2],[4]])

In [55]:
y.shape

(3, 1)

In [56]:
x+y

array([[2],
       [4],
       [7]])

In [57]:
np.add(y,x)

array([[2],
       [4],
       [7]])

Multiplication

In [58]:
np.multiply(x,y)

array([[ 1],
       [ 4],
       [12]])

In [59]:
x * y

array([[ 1],
       [ 4],
       [12]])

In [60]:
alpha = 2
alpha * y

array([[2],
       [4],
       [8]])

scaler comb

In [61]:
a, b = 2, 3
x, y = np.array([[2],[3]]), np.array([[4],[5]])

In [62]:
a * x + b * y

array([[16],
       [21]])

DOT products

In [63]:
x.T@y

array([[23]])

In [64]:
x = x.T
np.dot(x,y)

array([[23]])

In [ ]:
n