In [1]:
import numpy as np

creating multidimensional

In [3]:
my_arr = np.ones((3,3),dtype="int32")
my_arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

dimensions and size


In [4]:
my_arr.size

9

In [5]:
my_arr.ndim

2

In [6]:
my_arr.shape

(3, 3)

In [8]:
num_row = my_arr.shape[0]
num_row

3

In [9]:
num_col = my_arr.shape[1]
num_col

3

maths

In [11]:
np.sum(my_arr)

9

In [12]:
np.multiply(my_arr,3)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [13]:
np.divide(my_arr,3)

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])

transpose

In [15]:
my_arr.T

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])