In [96]:
import numpy as np

In [97]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


transpose of matrix

In [98]:
print(arr1.T)
print(arr2.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


identy matrix

In [99]:
i_mat = np.identity(3,dtype = "int32")
i_mat

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [100]:
arr1 + i_mat
arr2 + i_mat

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

reversing

In [101]:
arr1 = np.flip(arr1)
print(arr1)
arr2 = np.flip(arr2)
print(arr2)




[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


slicing and indexing

In [102]:

# arr2[1:3,1:3] = 1
# print(arr2)

mathmatics

In [103]:
sum_of_arr1 = np.sum(arr1)
print("sum of arr1: " ,sum_of_arr1)

sum_of_arr2 = np.sum(arr2)
print("sum of arr2: ",sum_of_arr2)


sum_of_both_arr = sum_of_arr1 + sum_of_arr2
print("The sum of both arr: ", sum_of_both_arr)


sum_arr = arr1 + arr2
print("The sum of both arr: ",np.sum(sum_arr))

sum of arr1:  45
sum of arr2:  45
The sum of both arr:  90
The sum of both arr:  90


In [104]:
mul_of_arr1 = np.multiply(arr1,2)
mul_of_arr2 = np.multiply(arr2,2)
mul_of_both_arr = mul_of_arr1 * mul_of_arr2
print("Multiplication of both arrays: \n", mul_of_both_arr)

arr_of_both = arr1 * arr2 * 2 * 2
print("\nArrays after element wise multiplication:\n", arr_of_both)

print("The sum of elemenet of mul of arr1 and arr2: ",np.sum(arr_of_both))

Multiplication of both arrays: 
 [[324 256 196]
 [144 100  64]
 [ 36  16   4]]

Arrays after element wise multiplication:
 [[324 256 196]
 [144 100  64]
 [ 36  16   4]]
The sum of elemenet of mul of arr1 and arr2:  1140


flatten

In [105]:
arr1.flatten()

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [107]:
arr1.ravel()

array([9, 8, 7, 6, 5, 4, 3, 2, 1])