In [21]:
import numpy as np

creating

In [22]:
my_arr = np.zeros(5, dtype="int32")
my_arr

array([0, 0, 0, 0, 0])

size and dimension

In [23]:
my_arr.size

5

In [24]:
my_arr.ndim

1

In [25]:
my_arr.shape

(5,)

math

In [27]:
# add
my_arr = my_arr + 1
print(my_arr)

# sub
my_arr = my_arr + 1
print(my_arr)

#mul
my_arr = my_arr * 2
print(my_arr)

#divide
my_arr = my_arr / 2
print(my_arr)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[4. 4. 4. 4. 4.]
[2. 2. 2. 2. 2.]
