Create all the elements one only one dimensional

In [5]:
import numpy as np

all one with the size of n

In [6]:
my_arr = np.ones(5)
my_arr

array([1., 1., 1., 1., 1.])

we can also specify the data type of element of array

In [7]:
my_arr = np.ones(5,dtype="int32")
my_arr

array([1, 1, 1, 1, 1])

dimension of array

In [8]:
my_arr.ndim

1

shape of array

In [9]:
my_arr.shape

(5,)

size of arr

In [10]:
my_arr.size

5

each element size

In [11]:
my_arr.itemsize

4

sum of array

In [12]:
submission = np.size(my_arr)
submission

5

multiplicaton

In [13]:
multiplication = np.multiply(my_arr,2)
print(multiplication)

mul2 = my_arr * 2
print(mul2)

[2 2 2 2 2]
[2 2 2 2 2]


division 

In [14]:
my_arr/2

array([0.5, 0.5, 0.5, 0.5, 0.5])

mathfuncations

In [15]:
#sin
sin_val = np.sin(my_arr)
print(sin_val)

#cos 
cos_val = np.cos(my_arr)
print(cos_val)

#tan
tan_val = np.tan(my_arr)
print(tan_val)

#arctan
arctan_val = np.arctan(my_arr)
print(arctan_val)

#arcsin
arcsin_val = np.arcsin(my_arr)
print(arcsin_val)


[0.84147098 0.84147098 0.84147098 0.84147098 0.84147098]
[0.54030231 0.54030231 0.54030231 0.54030231 0.54030231]
[1.55740772 1.55740772 1.55740772 1.55740772 1.55740772]
[0.78539816 0.78539816 0.78539816 0.78539816 0.78539816]
[1.57079633 1.57079633 1.57079633 1.57079633 1.57079633]


reshaping


indexing of array

In [26]:
print(my_arr[:])
print(my_arr[1::])
print(my_arr[-1:])

[1 1 1 1 1]
[1 1 1 1]
[1]


In [29]:
my_arr[my_arr>=1]

array([1, 1, 1, 1, 1])

In [30]:
my_arr >= 1

array([ True,  True,  True,  True,  True])

In [31]:
np.unique(my_arr)

array([1])

In [32]:
np.max(my_arr)

1

In [33]:
np.min(my_arr)

1

In [34]:
np.sum(my_arr)

5

In [35]:
np.exp(my_arr)

array([2.71828183, 2.71828183, 2.71828183, 2.71828183, 2.71828183])

In [36]:
np.log(my_arr)

array([0., 0., 0., 0., 0.])

In [37]:
np.log10(my_arr)

array([0., 0., 0., 0., 0.])

In [38]:
np.mean(my_arr)

1.0