In [1]:
import numpy as np

my_arr = np.arange(2,11).reshape(3,3)
print(my_arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
arr2 = np.arange(12,38)
print("The arr2 is: ",arr2)

The arr2 is:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [3]:
arr2 = np.flip(arr2)
print("THe reverse is: ",arr2)

THe reverse is:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]
